language: php

cache:
  directories:
    - $HOME/.composer/cache

env:
  - DEPENDENCIES=""

php:
  - 7.1
  - 7.2
  - 7.3

install:
  - travis_retry composer update --no-interaction --prefer-dist $DEPENDENCIES

script:
  - composer run-script check:composer
  - composer run-script check:lint
  - composer run-script check:cs
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.3" ]]; then composer run-script check:types; fi
  - composer run-script check:tests

after_script:
  - composer run-script coveralls
